/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [8.66KB] > /Users/matthewdavis/Downloads/lasershark_lab/scene-transformed.glb [579.64KB] (-6593%)
Author: m3org (https://sketchfab.com/m3org)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lasershark-lab-2174fa45ac874da8ac342b9d4833f4cd
Title: Lasershark Lab
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props: any) {
  const { nodes, materials } = useGLTF("/lasershark-lab-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.lasershark_lab001_screens_0.geometry}
        // material={materials.screens}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lasershark_lab001_base_0.geometry}
        material={materials.base}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.lasershark_lab001_alpha_0.geometry}
        material={materials.alpha}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
