/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [33.22KB] > /Users/matthewdavis/Downloads/stargate_lik-ish_ring_portal/scene-transformed.glb [127.65KB] (-284%)
Author: Kim.David.Hauser (https://sketchfab.com/Kim.David.Hauser)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stargate-lik-ish-ring-portal-b9dac9c49f46455294eb47eca8015052
Title: Stargate lik-ish Ring Portal
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Teleporter(props: any) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/teleporter-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(animations);

    actions["Scene"].play();
    setTimeout(() => {
      actions["Scene"].stop();
    }, 5000);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Torus" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              name="Torus_Material004_0"
              geometry={nodes.Torus_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              name="Torus_Material_0"
              geometry={nodes.Torus_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group
            name="Torus001"
            position={[0, 3, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              name="Torus001_Material004_0"
              geometry={nodes.Torus001_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              name="Torus001_Material_0"
              geometry={nodes.Torus001_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group name="Torus002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              name="Torus002_Material004_0"
              geometry={nodes.Torus002_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              name="Torus002_Material_0"
              geometry={nodes.Torus002_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group name="Torus003" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              name="Torus003_Material004_0"
              geometry={nodes.Torus003_Material004_0.geometry}
              material={materials["Material.004"]}
            />
            <mesh
              name="Torus003_Material_0"
              geometry={nodes.Torus003_Material_0.geometry}
              material={materials.Material}
            />
          </group>
        </group>
        <mesh
          name="Cylinder_Material003_0"
          geometry={nodes.Cylinder_Material003_0.geometry}
          material={materials["Material.003"]}
          position={[0.436, 0.777, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cylinder_Material002_0"
          geometry={nodes.Cylinder_Material002_0.geometry}
          material={materials["Material.002"]}
          position={[0.436, 0.777, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cylinder_Material005_0"
          geometry={nodes.Cylinder_Material005_0.geometry}
          material={materials["Material.005"]}
          position={[0.436, 0.777, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name="Cylinder_Material004_0"
          geometry={nodes.Cylinder_Material004_0.geometry}
          material={materials["Material.004"]}
          position={[0.436, 0.777, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/teleporter-transformed.glb");
